feat: sign content in privacyMode
Arianee/arianee-sdk pull request #287
Opened 2024-08-06 13:05 UTC by 0xWhiteleaf

2024-08-07 14:17 UTC, mvaullerin submitted a review, later dismissed

2024-08-08 14:53 UTC, stefdelec requested changes

2024-08-09 07:38 UTC, 0xWhiteleaf commented on packages/creator/src/lib/smartAssets/smartAssets.ts
> +      content = await injectProductIssuerSignature(
J'ai changé dans une autre PR pour avoir des noms plus cohérents et lisibles

2024-08-09 07:42 UTC, stefdelec approved these changes

2024-08-09 07:42 UTC, merged